services:
  # device_agent:
  #   image: spaneng/doover_device_agent:apps
  #   network_mode: host

  # sample_simulator:
  #   build: ./sample
  #   network_mode: host
  #   restart: unless-stopped
  #   depends_on:
  #     - device_agent
  #   environment:
  #     - APP_KEY=sim_app_key

  test_hydraulics_controller:
    build: ../
    network_mode: host
    restart: unless-stopped
    # depends_on:
    #   - device_agent
    #   - sample_simulator
    environment:
      - APP_KEY=hydraulics_controller_o7gvb
      # - CONFIG_FP=/app_config.json
    # volumes:
      # - ./app_config.json:/app_config.json
